package com.project.marketplace.model;

public enum Category {
    ELECTRONICS,
    FASHION,
    HOME_GARDEN,
    SPORTS_LEISURE,
    COLLECTIBLES_ART,
    MOTORS,
    TOYS_HOBBIES,
    BUSINESS_INDUSTRIAL,
    MUSIC_FILMS_BOOKS,
    HEALTH_BEAUTY,
    BABY,
    PETS_SUPPLIES,
    COMPUTERS_TABLETS,
    VIDEO_GAMES_CONSOLES,
    REAL_ESTATE,
    TRAVEL
}
